export { default as Welcomepage } from './welcomepage/Welcomepage';
export { default as Homepage } from './homepage/Homepage';
export { default as Aboutme } from './aboutme/Aboutme';
export { default as Projects } from './projects/Projects';
export { default as Blog } from './blog/Blog';
export { default as Contactme } from './contactme/Contactme';
export { default as BlogPostPage } from './Blogpostpage1/BlogPostPage';
export { default as Jsfatigue } from './jsfatigue/jsfatigue';
export { default as Aireactprojects } from './aireactprojects/Aireactprojects';
export { default as Aipersonalisedmarketing } from './aipersonalisedmarketing/Aipersonalisedmarketing'
export { default as Futurefrontend } from './futurefrontend/Futurefrontend'
export { default as Growthhacking } from './growthhacking/Growthhacking'
export { default as Growthhackingfrontend } from './growthhackingfrontend/Growthhackingfrontend'
export { default as Aiinonlinedating } from './aiinonlinedating/Aiinonlinedating'